from .workspaces import workspaces
from .clock import clock
from .battery import battery
from .system import system_indicators
from .volume import volume
from .brightness import brightness
from .network import network
from .bluetooth import bluetooth
from .power import power_button
from .dashboard import dashboard_window
